import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/admin/01072004');
  await page.getByText('Admin PanelPersonal').click();
  await page.getByRole('heading', { name: 'Admin Panel' }).click();
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Personal Details' }).click();
  await page.getByRole('main').click();
  await page.getByText('First NameMiddle NameLast').click();
  await page.getByText('First Name').click();
  await page.getByRole('textbox', { name: 'First Name' }).click();
  await page.getByText('Middle Name').click();
  await page.getByRole('textbox', { name: 'Middle Name' }).click();
  await page.getByText('Last Name').click();
  await page.getByRole('textbox', { name: 'Last Name' }).click();
  await page.getByText('Languages').click();
  await page.getByRole('textbox', { name: 'Languages' }).click();
  await page.getByText('Email').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByText('Phone Number').click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByText('What I Do').click();
  await page.getByRole('textbox', { name: 'What I Do' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).fill('09000000000');
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('textbox', { name: 'Phone Number' }).click();
  await page.getByRole('button', { name: 'Education' }).click();
  await page.getByRole('main').click();
  await page.getByText('EducationAdd EducationLevelSchool NameSchool AddressYear AttendedYear').click();
  await page.getByRole('heading', { name: 'Education' }).click();
  await page.getByRole('columnheader', { name: 'Level' }).click();
  await page.getByRole('columnheader', { name: 'School Name' }).click();
  await page.getByRole('columnheader', { name: 'School Address' }).click();
  await page.getByRole('columnheader', { name: 'Year Attended' }).click();
  await page.getByRole('columnheader', { name: 'Year Attended' }).click();
  await page.getByRole('columnheader', { name: 'Year Graduated' }).click();
  await page.getByRole('columnheader', { name: 'Year Graduated' }).click();
  await page.getByRole('cell', { name: 'tertiary' }).click();
  await page.getByText('tertiary').click();
  await page.getByRole('cell', { name: 'PUP' }).click();
  await page.getByRole('cell', { name: 'PUP' }).click();
  await page.getByRole('cell', { name: 'Laguna' }).click();
  await page.getByRole('cell', { name: '/1/2022' }).click();
  await page.getByRole('cell', { name: '/1/2026' }).click();
  await page.getByRole('columnheader', { name: 'Course' }).click();
  await page.getByRole('cell', { name: 'BSIT' }).click();
  await page.getByRole('columnheader', { name: 'Description' }).click();
  await page.getByRole('cell', { name: '-' }).click();
  await page.getByRole('columnheader', { name: 'Actions' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('Test');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('cell', { name: 'Test' }).click();
  await page.getByRole('button', { name: 'Update' }).click();
  await page.getByRole('textbox', { name: 'Description' }).click();
  await page.getByRole('textbox', { name: 'Description' }).fill('');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('cell', { name: '-' }).click();
  await page.getByRole('button', { name: 'Add Education' }).click();
  await page.locator('div').filter({ hasText: 'Add EducationLevel' }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Add Education$/ }).nth(1).click();
  await page.getByRole('heading', { name: 'Add Education' }).click();
  await page.locator('div').filter({ hasText: 'Level PrimarySecondaryTertiaryMasteralDoctorateSchool NameSchool AddressYear' }).nth(4).click();
  await page.getByRole('dialog').getByText('Level').click();
  await page.getByRole('combobox').selectOption('secondary');
  await page.getByRole('combobox').selectOption('tertiary');
  await page.getByRole('combobox').selectOption('masteral');
  await page.getByRole('combobox').selectOption('doctorate');
  await page.getByRole('combobox').selectOption('tertiary');
  await page.getByRole('dialog').getByText('School Name').click();
  await page.getByRole('textbox', { name: 'School Name' }).click();
  await page.getByRole('textbox', { name: 'School Name' }).fill(' pup');
  await page.getByRole('dialog').getByText('School Address').click();
  await page.getByRole('textbox', { name: 'School Name' }).click();
  await page.getByRole('dialog').getByText('School Address').click();
  await page.getByRole('textbox', { name: 'School Address' }).click();
  await page.getByRole('textbox', { name: 'School Address' }).fill('laguna');
  await page.getByRole('dialog').getByText('Year Attended').click();
  await page.getByRole('textbox', { name: 'Year Attended' }).click();
  await page.getByRole('textbox', { name: 'Year Attended' }).fill('2022');
  await page.getByRole('textbox', { name: 'Year Graduated (optional)' }).click();
  await page.getByText('Year Graduated (optional)').click();
  await page.getByText('Course (optional)').click();
  await page.getByRole('textbox', { name: 'Course (optional)' }).click();
  await page.getByText('Description (optional)').click();
  await page.getByRole('textbox', { name: 'Description (optional)' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Add Education' }).click();
  await page.getByText('EducationAdd EducationLevelSchool NameSchool AddressYear AttendedYear').click();
  await page.getByRole('row', { name: 'tertiary pup laguna 1/1/2022 - - - Update Delete' }).locator('span').click();
  await page.getByRole('cell', { name: 'pup', exact: true }).click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.locator('div').filter({ hasText: /^Delete Education$/ }).click();
  await page.getByText('Are you sure you want to delete pup? This action cannot be undone.CancelDelete').click();
  await page.getByText('Are you sure you want to').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.getByRole('button', { name: 'Close modal' }).click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete' }).click();
  await page.getByRole('main').click();
  await page.getByText('EducationAdd EducationLevelSchool NameSchool AddressYear AttendedYear').click();
  await page.getByRole('button', { name: 'Add Education' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Add Education' }).click();
  await page.getByRole('button', { name: 'Close modal' }).click();
  await page.getByRole('button', { name: 'Skills' }).click();
  await page.getByRole('main').click();
  await page.getByText('SkillsAdd Skill').click();
  await page.getByRole('button', { name: 'Add Skill' }).click();
  await page.locator('div').filter({ hasText: 'Add SkillImage URL (optional)' }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Add Skill$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: 'Image URL (optional)Skill' }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Image URL (optional)Skill' }).nth(4).click();
  await page.locator('div').filter({ hasText: 'Image URL (optional)Skill' }).nth(4).click();
  await page.getByText('Image URL (optional)').click();
  await page.getByText('Image URL (optional)').click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).fill('vsdv');
  await page.getByRole('dialog').getByText('Skill Name').click();
  await page.getByRole('dialog').getByText('Skill Name').click();
  await page.getByRole('textbox', { name: 'Skill Name' }).fill('d');
  await page.getByRole('textbox', { name: 'Skill Name' }).click();
  await page.getByRole('textbox', { name: 'Skill Name' }).fill('dvv');
  await page.getByRole('dialog').getByText('Category').click();
  await page.getByRole('combobox').selectOption('soft');
  await page.getByRole('combobox').selectOption('core');
  await page.getByText('Description (optional)').click();
  await page.locator('div').filter({ hasText: /^Description \(optional\)$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Description (optional)' }).click();
  await page.getByRole('textbox', { name: 'Description (optional)' }).fill('test description');
  await page.getByText('Proficiency Level (0-10,').click();
  await page.getByText('Proficiency Level (0-10,').click();
  await page.getByText('Proficiency Level (0-10,').click();
  await page.getByText('Proficiency Level (0-10,').click();
  await page.getByText('Proficiency Level (0-10,').click();
  await page.locator('div').filter({ hasText: 'Image URL (optional)Skill' }).nth(4).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Add Skill' }).click();
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Update' }).first().click();
  await page.getByRole('textbox', { name: 'Skill Name' }).click();
  await page.getByRole('textbox', { name: 'Skill Name' }).fill('test skill');
  await page.getByRole('textbox', { name: 'Image URL' }).click();
  await page.getByRole('textbox', { name: 'Image URL' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Image URL' }).fill('test');
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Update' }).first().click();
  await page.getByRole('textbox', { name: 'Skill Name' }).dblclick();
  await page.getByRole('textbox', { name: 'Skill Name' }).fill('test');
  await page.getByRole('textbox', { name: 'Image URL' }).dblclick();
  await page.getByRole('textbox', { name: 'Image URL' }).fill('test');
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.locator('div').filter({ hasText: 'Delete SkillAre you sure you' }).nth(2).click();
  await page.locator('div').filter({ hasText: /^Delete Skill$/ }).click();
  await page.locator('div').filter({ hasText: /^Delete Skill$/ }).click();
  await page.getByText('Are you sure you want to delete test? This action cannot be undone.CancelDelete').click();
  await page.getByText('CancelDelete').click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.getByText('Are you sure you want to delete test? This action cannot be undone.CancelDelete').click();
  await page.getByText('Are you sure you want to').click();
  await page.locator('.flex.justify-end > div:nth-child(2) > .bg-delete-button').click();
  await page.getByText('SkillsAdd SkillImageSkill').click();
  await page.getByRole('button', { name: 'Projects' }).click();
  await page.getByRole('main').click();
  await page.getByText('ProjectsAdd Project').click();
  await page.getByText('ProjectsAdd ProjectImageTitleStatusTechnologiesRoleStart DateEnd').click();
  await page.getByRole('columnheader', { name: 'Image' }).click();
  await page.getByRole('columnheader', { name: 'Title' }).click();
  await page.getByRole('columnheader', { name: 'Status' }).click();
  await page.getByRole('columnheader', { name: 'Technologies' }).click();
  await page.getByRole('columnheader', { name: 'Role' }).click();
  await page.getByRole('columnheader', { name: 'Start Date' }).click();
  await page.getByRole('columnheader', { name: 'End Date' }).click();
  await page.getByRole('columnheader', { name: 'Links' }).click();
  await page.getByRole('columnheader', { name: 'Actions' }).click();
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Update' }).first().click();
  await page.getByRole('textbox', { name: 'Role' }).click();
  await page.getByRole('cell', { name: 'Image URL webcom.png' }).click();
  await page.getByRole('cell', { name: 'Title Web Components Library' }).click();
  await page.getByRole('cell', { name: 'Status Ongoing' }).click();
  await page.getByRole('combobox').selectOption('finished');
  await page.getByRole('combobox').selectOption('cancelled');
  await page.getByRole('cell', { name: 'Technologies storybook, React' }).click();
  await page.getByRole('cell', { name: 'Role' }).click();
  await page.getByRole('cell', { name: 'Role' }).click();
  await page.getByRole('cell', { name: 'Start Date 2026-04-' }).click();
  await page.getByRole('cell', { name: 'Start Date 2026-04-' }).locator('label').click();
  await page.getByRole('cell', { name: 'Start Date 2026-04-' }).locator('label').click();
  await page.locator('tbody').getByText('End Date').click();
  await page.getByRole('textbox', { name: 'End Date' }).click();
  await page.getByRole('cell', { name: 'End Date' }).click();
  await page.getByText('Project LinkRepo Link').click();
  await page.getByText('Project Link').click();
  await page.getByText('Repo Link').click();
  await page.getByRole('cell', { name: 'Image URL webcom.png' }).click();
  await page.getByText('Image URL').click();
  await page.getByText('Image URL').click();
  await page.getByRole('cell', { name: 'Title Web Components Library' }).locator('label').click();
  await page.getByRole('textbox', { name: 'Title' }).click();
  await page.getByRole('cell', { name: 'Status Cancelled' }).locator('label').click();
  await page.getByRole('cell', { name: 'Technologies storybook, React' }).locator('label').click();
  await page.getByRole('textbox', { name: 'Technologies' }).click();
  await page.getByRole('cell', { name: 'Role' }).locator('label').click();
  await page.getByRole('cell', { name: 'Role' }).locator('label').click();
  await page.getByRole('cell', { name: 'Start Date 2026-04-' }).locator('label').click();
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).click();
  await page.locator('div').filter({ hasText: /^Add Project$/ }).nth(1).click();
  await page.getByText('Image URL (optional)').click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).click();
  await page.getByText('Project Title').click();
  await page.getByRole('textbox', { name: 'Project Title' }).click();
  await page.getByText('Project Description').click();
  await page.getByRole('textbox', { name: 'Project Description' }).click();
  await page.getByText('Project Type (optional)').click();
  await page.locator('div').filter({ hasText: /^Project Type \(optional\)$/ }).click();
  await page.locator('div').filter({ hasText: /^Project Type \(optional\)$/ }).click();
  await page.getByText('Role (optional)').click();
  await page.locator('div').filter({ hasText: /^Role \(optional\)$/ }).click();
  await page.getByText('Technologies Used').click();
  await page.getByRole('textbox', { name: 'Technologies Used' }).click();
  await page.getByText('Project Link (optional)').click();
  await page.getByRole('textbox', { name: 'Project Link (optional)' }).click();
  await page.getByText('Repository Link (optional)').click();
  await page.getByRole('textbox', { name: 'Repository Link (optional)' }).click();
  await page.getByRole('dialog').getByText('Start Date').click();
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await page.getByText('End Date (optional)').click();
  await page.getByRole('textbox', { name: 'End Date (optional)' }).click();
  await page.getByText('Project Status OngoingFinishedCancelled').click();
  await page.getByRole('combobox').selectOption('finished');
  await page.getByRole('combobox').selectOption('cancelled');
  await page.getByRole('combobox').selectOption('ongoing');
  await page.getByText('Currently Ongoing').click();
  await page.getByRole('checkbox', { name: 'Currently Ongoing' }).uncheck();
  await page.getByRole('checkbox', { name: 'Currently Ongoing' }).check();
  await page.getByText('Check this if the project is').click();
  await page.getByRole('dialog').getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('main').click();
  await page.getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).click();
  await page.getByRole('textbox', { name: 'Image URL (optional)' }).fill('test');
  await page.getByRole('textbox', { name: 'Project Title' }).click();
  await page.getByRole('textbox', { name: 'Project Title' }).fill('test');
  await page.getByRole('textbox', { name: 'Start Date' }).click();
  await page.getByRole('textbox', { name: 'Start Date' }).fill('2022');
  await page.getByRole('dialog').getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('textbox', { name: 'Role (optional)' }).click();
  await page.getByRole('textbox', { name: 'Role (optional)' }).fill('test');
  await page.getByRole('textbox', { name: 'Project Description' }).click();
  await page.getByRole('textbox', { name: 'Project Description' }).fill('test');
  await page.getByRole('textbox', { name: 'Technologies Used' }).click();
  await page.getByRole('textbox', { name: 'Technologies Used' }).fill('test');
  await page.getByRole('dialog').getByRole('button', { name: 'Add Project' }).click();
  await page.getByRole('main').click();
  await page.getByText('ProjectsAdd Project').click();
  await page.getByText('ProjectsAdd ProjectImageTitleStatusTechnologiesRoleStart DateEnd').click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.locator('div').filter({ hasText: /^Delete Project$/ }).click();
  await page.getByText('Are you sure you want to delete test? This action cannot be undone.CancelDelete').click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Delete' }).first().click();
  await page.getByRole('dialog').getByRole('button', { name: 'Delete' }).click();
});